### PR TITLE
React role

### PR DESCRIPTION
**Pull request by ravstar52**

### CODE REVIEW

**Comment by ravstar52** [comment]
Oh that's not good.

I'll fix it in the morning

**Comment by ravstar52** [comment]
Okay, that seemed to fix it. Dunno why, but I'll take it.

Ready for peer review and merge!

**Comment by ravstar52** [comment]
OH MY GOD. the previous build passed just fine. Now what?

**Comment by viljoviitanen** [comment]
Working now, with discordrb library updated to 3.2.1 + its dependencies.

Lane will need to run `bundle update discordrb` manually after this update before bot restart.

**Pull request merged**
